import '../assets/css/globals.css'
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";


export const metadata = {
  title: 'eCocktail',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
      <html>
          <body style={{display: "flex", flexDirection: "column", justifyContent: "space-between" }}>
              <NavBar />
              {children}
              <Footer />
          </body>
      </html>
  )
}
