import '../assets/css/globals.css'
import NavBar from "@/components/NavBar";


export const metadata = {
  title: 'eCocktail',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
      <html>
          <body>
              <NavBar />
              {children}
          </body>
      </html>
  )
}
